trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Setup Java 17'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: false 
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Executar Bateria de Testes (Maven)'
  env:
    PORTAL_LOGIN: $(PORTAL_LOGIN)
    PORTAL_SENHA: $(PORTAL_SENHA)
    LOGIN: $(LOGIN)
    SENHA: $(SENHA)
    API_ENVIRONMENT: $(API_ENVIRONMENT)
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Automação de API'
    mergeTestResults: true
  condition: succeededOrFailed()
  displayName: 'Publicar Resultados Nativos do Azure DevOps'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'target/api-report/'
    artifact: 'relatorio-testes-html'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
  displayName: 'Fazer Upload do Relatório HTML Customizado'
