name: CI API Tests

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite execução manual pelo painel do GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup do Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Executar Bateria de Testes (Maven)
      run: mvn clean test
      continue-on-error: true # Permite gerar o relatório mesmo se algum teste falhar

    - name: Fazer Upload do Relatório Surefire (HTML/XML)
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-testes
        path: target/surefire-reports/
        retention-days: 7
