name: CI API Tests

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite execução manual pelo painel do GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup do Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Executar Bateria de Testes (Maven)
      env:
        PORTAL_LOGIN: ${{ secrets.PORTAL_LOGIN }}
        PORTAL_SENHA: ${{ secrets.PORTAL_SENHA }}
        LOGIN: ${{ secrets.LOGIN }}
        SENHA: ${{ secrets.SENHA }}
        API_ENVIRONMENT: ${{ secrets.API_ENVIRONMENT }}
      run: mvn clean test
      continue-on-error: true # Permite gerar o relatório mesmo se algum teste falhar

    - name: Fazer Upload do Relatório Surefire e HTML
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-testes
        path: |
          target/surefire-reports/
          target/api-report/
        retention-days: 7
